env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
  - prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - prettier
rules:
  prettier/prettier: ["error"]
  react/jsx-one-expression-per-line: off
  react/jsx-curly-newline: off
  react/jsx-wrap-multilines: off
  no-multiple-empty-lines: [error, { max: 1, maxBOF: 0, maxEOF: 0 }]
  no-underscore-dangle:  ['error', { 'allow': ['_id', '__typename'] }]
  react/prop-types: 0
